# Generated by Django 6.0.5 on 2026-06-10 04:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_fa', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80)),
                ('name_fa', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(allow_unicode=True, max_length=40, unique=True)),
                ('accent_color', models.CharField(default='#ffcc00', help_text='Hex color used for article accents (e.g. #ffcc00)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour (e.g. #ffcc00).', regex='^#[0-9a-fA-F]{6}$')])),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Post type',
                'verbose_name_plural': 'Post types',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_fa', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='posts.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('author_name', models.CharField(blank=True, help_text='First and last name, or team name', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Short intro / excerpt')),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/covers/')),
                ('cover_alt', models.CharField(blank=True, help_text='Describe the image for screen readers (leave blank if purely decorative)', max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='posts/files/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Show?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.category')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_posts', to=settings.AUTH_USER_MODEL)),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.posttype')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.subcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='posts.tag')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
