# Generated by Django 6.0.5 on 2026-06-24 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_subcategory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'is_visible'], name='post_type_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='post_title_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author_name'], name='post_author_idx'),
        ),
    ]
