# Generated by Django 6.0.5 on 2026-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_post_type_visible_idx_post_post_title_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Views'),
        ),
    ]
