# Generated by Django 6.0.5 on 2026-06-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unique_view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Unique Views'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total Views'),
        ),
    ]
