# Generated by Django 6.0.5 on 2026-06-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_unique_view_count_alter_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_md_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/md/', verbose_name='Markdown File / فایل مارک\u200cداون'),
        ),
    ]
