# Generated by Django 6.0.5 on 2026-06-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_add_body_md_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override auto-calculated reading time. Leave blank for automatic.', null=True, verbose_name='Reading Time Override (min)'),
        ),
    ]
