# Generated by Django 6.0.5 on 2026-07-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_reading_time_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Show?'),
        ),
    ]
