# Generated by Django 6.0.5 on 2026-06-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Leave blank for no expiration.', null=True, verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'Site Alert',
                'verbose_name_plural': 'Site Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
