# Generated by Django 6.0.5 on 2026-06-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bilingual_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['nav_order', 'title_en'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='sitealert',
            name='message_en',
            field=models.TextField(verbose_name='Message (English)'),
        ),
        migrations.AlterField(
            model_name='sitealert',
            name='message_fa',
            field=models.TextField(blank=True, verbose_name='Message (Persian)'),
        ),
        migrations.AlterField(
            model_name='sitealert',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='sitealert',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Persian)'),
        ),
    ]
