# Generated by Django 6.0.5 on 2026-06-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (EN)')),
                ('name_fa', models.CharField(blank=True, max_length=120, verbose_name='Name (FA)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_fa', models.TextField(blank=True, verbose_name='Description (FA)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='Sticky')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='View count')),
                ('reply_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Reply count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.board', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'ordering': ['-is_sticky', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Body')),
                ('is_first_post', models.BooleanField(default=False, verbose_name='First post')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.thread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'Forum Post',
                'verbose_name_plural': 'Forum Posts',
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['board', 'is_deleted', '-updated_at'], name='thread_board_active_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['thread', 'is_deleted', 'created_at'], name='forumpost_thread_active_idx'),
        ),
    ]
