# Generated by Django 6.0.5 on 2026-06-24 04:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, validators=[accounts.models._validate_safe_url]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, validators=[accounts.models._validate_safe_url]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, validators=[accounts.models._validate_safe_url]),
        ),
    ]
