# Generated by Django 6.0.5 on 2026-06-25 05:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_fa', models.CharField(blank=True, max_length=150, verbose_name='Persian name')),
                ('description', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, help_text='Optional badge/icon image, processed to 256x256 JPEG', null=True, upload_to='certificates/icons/')),
                ('accent_color', models.CharField(default='#4f46e5', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour (e.g. #ffcc00).', regex='^#[0-9a-fA-F]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.certificate')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_certificates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Certificate',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'is_visible'], name='usercert_user_visible_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'certificate'), name='unique_user_certificate')],
            },
        ),
    ]
